### ISSUE TITLE
JS type annotations on Mnemonic don't make sense (copied from Address?)

### ISSUE THREAD

**Issue by dskloet** [bitpay/bitcore-mnemonic#14]
The JS doc above Mnemonic says

```
 * @param {*} data - The encoded data in various formats
 * @param {Network|String|number} [network] - The network: 'livenet' or 'testnet'
 * @param {String} [type] - The type of address: 'script' or 'pubkey'
 * @returns {Address} A new valid and frozen instance of an Address
```

This has nothing to do with Mnemonic.

https://github.com/bitpay/bitcore-mnemonic/blob/master/lib/mnemonic.js#L27

**Comment by maraoz** [comment]
ACK

**Comment by fanatid** [comment]
[Mnemonic.toHDPrivateKey](https://github.com/bitpay/bitcore-mnemonic/blob/fede83dc5dcee5661562c7c9565101c6318c367b/lib/mnemonic.js#L196) also have wrong JS doc..
