### ISSUE TITLE
Should there be a "Mnemonic.fromHDPrivateKey()"

### ISSUE THREAD

**Issue by throughnothing** [bitpay/bitcore-mnemonic#15]
If you've already generated a `bitcore.HDPrivateKey()`, should there be a way to pass it into `Mnemonic` to get the mnemonic phrase for it.  It doesn't seem like you can do that currently, you have to generate the `HDPrivateKey` with `Mnemonic`.

**Comment by Giszmo** [comment]
The Mnemonic needs the wordlist as an additional input. Also [HDPrivateKey.fromSeed()](https://github.com/bitpay/bitcore/blob/master/lib/hdprivatekey.js#L356) looks pretty one-way thanks to a hash function. But to be honest, exactly this linked line is unclear to me.

**Comment by nilnullzip** [comment]
Not possible. The mnemonic sentence is hashed to arrive at the seed that is used to generate the HDPrivateKey. So no way to go backwards.

> https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

This issue should be closed.

**Comment by throughnothing** [comment]
@nilnullzip thanks, that definitely makes sense, I didn't realize that.  So wallets that enable you to see the mnemonic seed if/when you want, have to store that mnemonic data separately, in addition to the Private Key (or re-generate the key from the mnemonic every load).
