### ISSUE TITLE
FR generated invalid words

### ISSUE THREAD

**Issue by matiu** [bitpay/bitcore-mnemonic#31]
1) Credentials Should verify roundtrip create/from with fr/passphrase:
     Mnemonic string is invalid: 
```
caution opprimer époque belote devenir ficeler filleul caneton apologie nectar frapper fouiller
```

**Comment by greggzigler** [comment]
Mnemonic._belongsToWordlist  seems to look at only the first word of the mnemonic and choose a dictionary based on the first word. Since 'caution' is also in the English dictionary, it returns that.

**Comment by braydonf** [comment]
Fixed in https://github.com/bitpay/bitcore-mnemonic/pull/32
