### ISSUE TITLE
Hi, how to use it in android?

### ISSUE THREAD

**Issue by tianqiujie** [bitpay/bitcore-mnemonic#59]
is there any sdk for android ? or java ?

**Comment by yuyaogawa** [comment]
You might find it from BitcoinJ. Look up [this](https://github.com/bitcoinj/bitcoinj/blob/master/core/src/main/java/org/bitcoinj/crypto/MnemonicCode.java)

**Comment by cubo1123** [comment]
do you had success implementing it on android?

**Comment by matiu** [comment]
This is a javascript library. You can use it on Android using a browser, like Chrome; or create a native app thru Electron, or NW.JS
